[package]
name = "time"
version = "0.0.1"
edition = "2018"

[dependencies]
http = "0.1"
lambda_runtime = "0.2.0"
chrono = "0.4"

[dependencies.now_rust]
git = "https://github.com/anmonteiro/now-rust"
rev = "master"